modLoader = "javafml"
loaderVersion = "[46,)"
license = "Custom"

[[mods]]
modId = "bakery"
version = "${version}"
displayName = "[Let's Do] Bakery"
authors = "Satisfy"
description = '''
Build your own bakery, bake the finest pastries, delicious bread, and sweet cakes!'''
logoFile = "pack.png"

[[dependencies.bakery]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bakery]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bakery]]
modId = "doapi"
mandatory = true
versionRange = "[1.2.9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bakery]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bakery]]
modId = "farm_and_charm"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"